package com.sap.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController()
@RequestMapping(path = "/users")
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path = "/") // Map ONLY GET Requests
    public @ResponseBody
    User addUser(@RequestParam String name
            , @RequestParam String email
            , @RequestParam String locale) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setLocale(locale);
        userRepository.save(n);
        return n;
    }

    @GetMapping(path = "/")
    public @ResponseBody
    Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path = "/{email}")
    public @ResponseBody
    User getUserByEmail(@PathVariable("email") String email) {
        return userRepository.findByEmail(email).orElseThrow(() -> new NotFoundError());
    }

}
